# cc83 but finetune with greater hotspot dropout and lower minimum hotspots
train:
  seed: 0
  ckpt_path: ""
  batch_size: 32
  max_epochs: 10000
  eval_freq: 8000000 # seconds
  checkpoint_freq: 1
  checkpoints: []
  lr: 0.0001
  warmup_steps: 1000
  decay_steps: 2_000_000
  use_amp: False
  clip_grad_norm: True
  grad_clip_val: 1.0
  weight_decay: 0.0
  n_eval_samples: 10
  length_ranges_per_chain: [[166, 188]]
  sc_num_seqs: 4
  eval_loss_t: [0.1, 0.3, 0.5, 0.7, 0.9]
  self_cond_train_prob: 0.9
  subsample_eval_set: 0.05
  crop_conditional: True
  crop_cond:
    contiguous_prob: 0.05
    discontiguous_prob: 0.45
    sidechain_prob: 0.9
    sidechain_only_prob: 0.0
    max_span_len: 12
    max_discontiguous_res: 24
    dist_threshold: 45.0
    recenter_coords: True
    multichain_prob: 0.45
    hotspot_min: 0
    hotspot_max: 8
    hotspot_dropout: 0.5
    paratope_prob: 0.1

data:
  pdb_paths:
    [
      "/your/path/to/boltz_interfaces",
      "/your/path/to/augmented_ingraham_cath_bugfree",
    ]
  mixing_ratios: [0.5, 0.5]
  fixed_size: 512
  n_aatype_tokens: 21
  se3_data_augment: True
  translation_scale: 1.0
  chain_residx_gap: 200 # residue index gap for chain breaks for PDBs with multiple chains
  sigma_data: 10.01
  auto_calc_sigma_data: True # If true, override sigma_data with value computed at runtime
  n_examples_for_sigma_data: 500 # Number of examples to use for computing sigma_data
  dummy_fill_mode: "zero" # fill ghost side chain atoms with one of ["zero", "CA", "CB"]
  subset: [2.0, "designable_"] # for AI-CATH, can be 'designable' or 'all' ; for boltz_interface, the resolution cutoff

diffusion:
  training:
    function: "lognormal"
    psigma_mean: -0.5
    psigma_std: 1.5
  sampling:
    function: "uniform"
    s_min: 0.001
    s_max: 80

model:
  task: "backbone" # 'backbone', 'allatom', 'seqdes', 'codesign'
  pretrained_modules: [] # 'struct_model', 'mpnn_model'
  struct_model_checkpoint: ""
  mpnn_model_checkpoint: ""
  crop_conditional: True
  conditioning_style: "concat_hotspot" # 'concat', 'noise_residual', 'concat_and_noise_residual'
  compute_loss_on_all_atoms: false
  struct_model:
    arch: "dit"
    n_atoms: 37
    n_channel: 256
    noise_cond_mult: 4
    uvit:
      patch_size: 1
      n_layers: 10
      n_heads: 8
      dim_head: 32
      n_filt_per_layer: []
      n_blocks_per_layer: 2
      cat_pwd_to_conv: False
      conv_skip_connection: False
      position_embedding_type: "relative"
      position_embedding_max: 32
  mpnn_model:
    use_self_conditioning: True
    label_smoothing: 0.1
    n_channel: 128
    n_layers: 3
    n_neighbors: 32
    noise_cond_mult: 4
