name: Code Quality

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # Official pre-commit action (runs hooks from .pre-commit-config.yaml). :contentReference[oaicite:11]{index=11}
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v3

      - name: Install dev deps into runner Python
        run: uv pip install --system -e ".[dev]"

      - name: Run mypy
        run: mypy --python-version 3.12
