name: Dependency Update

on:
    schedule:
        # Run every Monday at 9 AM UTC
        - cron: "0 9 * * 1"
    workflow_dispatch:

jobs:
    update-dependencies:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Update dependencies
              run: |
                  uv pip install --upgrade pip
                  uv pip install -e .
                  uv pip list --outdated

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "chore: update dependencies"
                  title: "chore: update dependencies"
                  body: |
                      ## Dependency Updates

                      This PR updates project dependencies to their latest versions.

                      ### Updated Dependencies
                      - Check the diff for specific version changes

                      ### Testing
                      - [ ] All tests pass
                      - [ ] No breaking changes detected
                      - [ ] Documentation updated if needed

                      ### Review Checklist
                      - [ ] Review dependency changes for security implications
                      - [ ] Verify compatibility with existing code
                      - [ ] Test with sample configurations
                  branch: dependency-updates
                  delete-branch: true
