name: Documentation

on:
    push:
        branches: [main]
        paths:
            - "README.md"
            - "docs/**"
            - "src/protpardelle/**"
            - ".github/copilot-instructions.md"
    pull_request:
        branches: [main]
        paths:
            - "README.md"
            - "docs/**"
            - "src/protpardelle/**"
            - ".github/copilot-instructions.md"
    workflow_dispatch:

jobs:
    build-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Install documentation dependencies
              run: |
                  uv pip install sphinx sphinx-rtd-theme myst-parser sphinx-autodoc-typehints
                  uv pip install -e .

            - name: Create documentation structure
              run: |
                  mkdir -p docs
                  cat > docs/conf.py << 'EOF'
                  import os
                  import sys
                  sys.path.insert(0, os.path.abspath('../../src'))

                  project = 'Protpardelle-1c'
                  copyright = '2024, Stanford University'
                  author = 'Tianyu Lu, Richard Shuai, Petr Kouba, Zhaoyang Li, Yilin Chen, Akio Shirali, Jinho Kim, Po-Ssu Huang'

                  extensions = [
                      'sphinx.ext.autodoc',
                      'sphinx.ext.viewcode',
                      'sphinx.ext.napoleon',
                      'sphinx.ext.intersphinx',
                      'myst_parser',
                      'sphinx_autodoc_typehints'
                  ]

                  templates_path = ['_templates']
                  exclude_patterns = []

                  html_theme = 'sphinx_rtd_theme'
                  html_static_path = ['_static']

                  autodoc_default_options = {
                      'members': True,
                      'member-order': 'bysource',
                      'special-members': '__init__',
                      'undoc-members': True,
                      'exclude-members': '__weakref__'
                  }
                  EOF

                  cat > docs/index.rst << 'EOF'
                  Protpardelle-1c Documentation
                  =============================

                  .. toctree::
                     :maxdepth: 2
                     :caption: Contents:

                     installation
                     api/index
                     examples
                     contributing

                  Indices and tables
                  ==================

                  * :ref:`genindex`
                  * :ref:`modindex`
                  * :ref:`search`
                  EOF

                  cat > docs/installation.rst << 'EOF'
                  Installation
                  ============

                  See the main README.md for installation instructions.
                  EOF

                  cat > docs/api/index.rst << 'EOF'
                  API Reference
                  ============

                  .. toctree::
                     :maxdepth: 2

                     core
                     data
                     integrations
                     common
                  EOF

                  cat > docs/api/core.rst << 'EOF'
                  Core Modules
                  ============

                  .. automodule:: protpardelle.core.models
                     :members:

                  .. automodule:: protpardelle.core.diffusion
                     :members:

                  .. automodule:: protpardelle.core.modules
                     :members:
                  EOF

                  cat > docs/api/data.rst << 'EOF'
                  Data Modules
                  ===========

                  .. automodule:: protpardelle.data.pdb_io
                     :members:

                  .. automodule:: protpardelle.data.dataset
                     :members:

                  .. automodule:: protpardelle.data.motif
                     :members:

                  .. automodule:: protpardelle.data.atom
                     :members:
                  EOF

                  cat > docs/api/integrations.rst << 'EOF'
                  Integration Modules
                  ===================

                  .. automodule:: protpardelle.integrations.esmfold
                     :members:

                  .. automodule:: protpardelle.integrations.protein_mpnn
                     :members:
                  EOF

                  cat > docs/api/common.rst << 'EOF'
                  Common Modules
                  ==============

                  .. automodule:: protpardelle.common.residue_constants
                     :members:

                  .. automodule:: protpardelle.common.protein
                     :members:
                  EOF

                  cat > docs/examples.rst << 'EOF'
                  Examples
                  ========

                  See the examples/ directory for usage examples.
                  EOF

                  cat > docs/contributing.rst << 'EOF'
                  Contributing
                  ============

                  See the main README.md for contributing guidelines.
                  EOF

            - name: Build documentation
              run: |
                  cd docs
                  sphinx-build -b html . _build/html

            - name: Upload documentation artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: documentation
                  path: docs/_build/html/

    lint-docs:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install documentation linting tools
              run: |
                  pip install markdownlint-cli2 textlint

            - name: Lint README.md
              run: |
                  markdownlint README.md || true

            - name: Lint copilot instructions
              run: |
                  markdownlint .github/copilot-instructions.md || true

            - name: Check for broken links
              run: |
                  pip install markdown-link-check
                  markdown-link-check README.md || true

    deploy-docs:
        runs-on: ubuntu-latest
        needs: [build-docs]
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        permissions:
            contents: write
            pages: write
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Download documentation artifacts
              uses: actions/download-artifact@v4
              with:
                  name: documentation
                  path: docs/_build/html/

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/_build/html/
                  cname: protpardelle-1c.readthedocs.io
