name: Status

on:
    schedule:
        # Run daily at 2 AM UTC
        - cron: "0 2 * * *"
    workflow_dispatch:

jobs:
    status-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"

            - name: Install dependencies
              run: |
                  uv pip install --upgrade pip
                  uv pip install torch --index-url https://download.pytorch.org/whl/cpu
                  uv pip install -e .[dev]

            - name: Run basic health checks
              run: |
                  echo "Running basic health checks..."

                  # Test imports
                  python -c "
                  import protpardelle
                  print(f'✓ Protpardelle version: {protpardelle.__version__}')
                  "

                  # Test core modules
                  python -c "
                  from protpardelle.core import models, diffusion, modules
                  from protpardelle.data import pdb_io, dataset, motif, atom
                  from protpardelle.common import residue_constants, protein
                  print('✓ Core modules imported successfully')
                  "

                  # Test CLI entry points
                  python -c "
                  from protpardelle import sample, train, evaluate, likelihood
                  print('✓ CLI modules imported successfully')
                  "

                  # Test configuration loading
                  python -c "
                  from protpardelle.configs import TrainingConfig, SamplingConfig, RunningConfig
                  print('✓ Configuration classes loaded successfully')
                  "

                  echo "✓ All health checks passed"

            - name: Check test coverage
              run: |
                  uv run pytest tests/ -m "not slow and not gpu and not requires_model" --cov=src/protpardelle --cov-report=term-missing --cov-report=xml
              continue-on-error: true

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              if: always()
              with:
                  file: ./coverage.xml
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: false
